WIP: Address LEDs individually
tkhduracell/node-lightpack-led pull request #1
Opened 2019-01-24 16:38 UTC by seccubus

This PR allows LED's to be addressed per channel instead of all channels in one go.

Attention this is currently untested code.

2019-01-25 13:03 UTC, seccubus commented
@tkhduracell can you merge please. I need this for a little project.

2019-01-25 17:16 UTC, tkhduracell commented
I will asap.

On Fri, Jan 25, 2019, 14:03 Frank Breedijk <notifications@github.com wrote:

> @tkhduracell <https://github.com/tkhduracell> can you merge please. I
> need this for a little project.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/tkhduracell/node-lightpack-led/pull/1#issuecomment-457566319>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AA9fnykm4ooXURMZETjJREo1RQ-puRPnks5vGwCzgaJpZM4aRQkZ>
> .
>

2019-01-25 18:24 UTC, MrSeccubus commented
Cool, thanks.

Sent from my mobile device, sorry for the typyos.

2019-01-26 15:29 UTC, tkhduracell requested changes
Added some comments, 
Not sure about the t package really, is this a common practice? I suggest creating just a examples folder?

2019-01-26 15:29 UTC, tkhduracell commented on t/package.json
> +  "name": "node-lightpack-led-test",
@seccubus Why is this a separate package isn't the devDependencies sufficient?

2019-01-26 15:29 UTC, tkhduracell commented on t/arraytest.js
> +const lp = require('node-lightpack-led');
Maybe we could call this package examples instead?

2019-01-26 15:29 UTC, tkhduracell commented on t/node-lightpack-led
> +..
what is this?

2019-01-26 15:29 UTC, tkhduracell commented on t/test.sh
> +#!/bin/bash
rename like examples/run-examples.js

2019-01-26 15:29 UTC, tkhduracell commented on t/arraytest.js
> +   	Atomics.wait(new Int32Array(new SharedArrayBuffer(4)),0,0,n);
Haven't seen this before. Isn't await sleep(1000) something we could use? Given sleep is implemented as a delay promise?

2019-01-26 15:29 UTC, tkhduracell commented on index.js
> +    command[buffIndex++] = (color[arrayIndex].r & 0x0FF0) >> 4
Should we maybe extract a `const ledColor = color[arrayIndex]`

2019-01-26 15:29 UTC, tkhduracell commented on README.md
> +        device.setColorArray(colors, bedug, repeatLast );
Typo `bedug`? 
Also, should we move the debug parameter to be the last argument, for consistency? 
Finally, I think getDevice() in `**Address leds individually**` and `**Set color of leds to red**` is a typo, it should be getDevices() right?

2019-01-26 15:29 UTC, tkhduracell commented
@seccubus Ping!

2019-01-26 18:00 UTC, seccubus commented
Examples folder works for me. I’m not a node developer myself, just a guy tinkering with LEDs. ;)

2019-01-26 18:02 UTC, seccubus commented on t/arraytest.js
> +const lp = require('node-lightpack-led');
I’m fine with that. I’m not a node developer, so don’t know the conventions, but I wantes to leave some test/example code.

2019-01-26 18:03 UTC, seccubus commented on t/arraytest.js
> +   	Atomics.wait(new Int32Array(new SharedArrayBuffer(4)),0,0,n);
This is what I found when googling it. It tried await sleep and could not get it to work in node 6 on AWS greengrass.

2019-01-26 18:04 UTC, seccubus commented on t/node-lightpack-led
> +..
Teat/example code. The t directoey is a perl convention.

2019-01-26 18:04 UTC, seccubus commented on t/package.json
> +  "name": "node-lightpack-led-test",
Did not know how to solve this properly.

2019-01-26 18:04 UTC, seccubus commented on t/test.sh
> +#!/bin/bash
Will do.

2019-01-26 19:03 UTC, tkhduracell commented on t/package.json
> +  "name": "node-lightpack-led-test",
In the package.json you can fill both the "dependencies" and the "devDependencies" with the different dependencies you need. I think we can remove t/package.json.

2019-01-26 19:04 UTC, tkhduracell commented on t/arraytest.js
> +const lp = require('node-lightpack-led');
Okay, cool, no problem I will guide you through it! :)

2019-01-26 19:04 UTC, tkhduracell commented on t/node-lightpack-led
> +..
This file we can remove :)

2019-01-26 19:14 UTC, tkhduracell commented on t/arraytest.js
> +   	Atomics.wait(new Int32Array(new SharedArrayBuffer(4)),0,0,n);
Yes, true, you will have problems with this is you need node 6 to work. There is also the more traditional setTimeout(t => { something(); }, 1000) but that is async. 

I suggest
```js
const sleep = (seconds) => {
    return new Promise((resolve, reject) => {
        setTimeout(resolve, (seconds * 1000));
    });
};


sleep(1000)
   .then(() => stuff1())
   .then(() => sleep(1000))
   .then(() => stuff2())
   .then(() => sleep(1000))
   .then(() => stuff3())
```

2019-01-26 19:20 UTC, tkhduracell commented
Cool, ping me when you implemented the changes. 
Rename `t/` -> `examlpes/`
Remove the extra files.

2019-01-26 19:21 UTC, seccubus commented on t/package.json
> +  "name": "node-lightpack-led-test",
This should be resolved now.

2019-01-26 19:21 UTC, seccubus commented on t/arraytest.js
> +const lp = require('node-lightpack-led');
Should be resolved.

2019-01-26 19:23 UTC, MrSeccubus commented on t/node-lightpack-led
> +..
It's a symlink to the base package. Without it the bash file won't run.
I've added it again.

2019-01-26 19:24 UTC, MrSeccubus commented on t/test.sh
> +#!/bin/bash
Done

2019-01-26 19:26 UTC, MrSeccubus commented on t/arraytest.js
> +   	Atomics.wait(new Int32Array(new SharedArrayBuffer(4)),0,0,n);
It's quite complex to use in a loop as it would turn the loops into reentrive/recursive programming.

E.g. how would we do this:
```js
let inc=25
for (let x=0; x <= 255; x+=inc ) {
	    msleep(150);
	    leds(x,0,0);
}
for (let x=0; x <= 255; x+=inc ) {
	    msleep(150);
	    leds(0,x,0);
}
```

2019-01-26 19:28 UTC, MrSeccubus commented on index.js
> +    command[buffIndex++] = (color[arrayIndex].r & 0x0FF0) >> 4
Done.

2019-01-26 19:35 UTC, seccubus commented on README.md
> +        device.setColorArray(colors, bedug, repeatLast );
getDevice() vs. getDevices() is actually a typo I copied and from your example. ;) I fixed them both...

Debug is now the last parameter.

2019-01-26 19:36 UTC, seccubus commented
@tkhduracell  pong

2019-01-26 21:37 UTC, tkhduracell commented on examples/node-lightpack-led
> +..
Remove this file

2019-01-26 21:37 UTC, tkhduracell commented on examples/node_modules
> +../node_modules/
Remove this file

2019-01-26 21:39 UTC, tkhduracell commented on examples/run-examples.sh
> +export NODE_PATH=".:./node_modules"
I don't think this is necessary. You can have this script locally.

2019-01-26 21:42 UTC, tkhduracell commented on index.js
> +    ledColor = color[arrayIndex]
const ledColor = ..

2019-01-26 21:45 UTC, tkhduracell commented
@seccubus Just a few more things... Then we ready!

2019-01-26 22:46 UTC, seccubus commented on index.js
> +    ledColor = color[arrayIndex]
pardon my ignorance, but why a constant, since it is actually different every iteration of the loop? Should it not be a var?
I left the lightpack at the office, so I cannot test today/tomorrow.

2019-01-26 22:47 UTC, seccubus commented on examples/run-examples.sh
> +export NODE_PATH=".:./node_modules"
I could not get it tto run otherwise...

2019-01-26 22:55 UTC, tkhduracell commented on examples/run-examples.sh
> +export NODE_PATH=".:./node_modules"
Yes, but this is not needed for the module, you can use this in your own project or locally, but wouldn't say it belongs here in this npm module.

2019-01-26 22:56 UTC, tkhduracell commented on t/node-lightpack-led
> +..
Yes, sure you might need this locally, but this is not needed for the module, you can use this in your own project or locally, but wouldn't say it belongs here in this npm module.

2019-01-26 22:59 UTC, tkhduracell commented on index.js
> +    ledColor = color[arrayIndex]
It's constant (not reassignable) within the scope of for-block execution.
https://medium.com/javascript-scene/javascript-es6-var-let-or-const-ba58b8dcde75

I would say it is a const :)

2019-01-26 23:09 UTC, tkhduracell approved these changes

2019-01-26 23:10 UTC, merged

2019-01-26 23:10 UTC, tkhduracell commented
@seccubus Thanks for you contribution 👍

2019-01-26 23:12 UTC, tkhduracell commented on t/arraytest.js
> +   	Atomics.wait(new Int32Array(new SharedArrayBuffer(4)),0,0,n);
That is indeed tricker unless you have async/await